name: Ingest and Terraform Apply

on:
  push:
    paths:
      - 'ingest/**'
      - 'infra/**'

jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@v3
      - name: Build and push ingest Docker image
        working-directory: ./ingest
        run: make

  terraform_apply:
    runs-on: ubuntu-latest
    needs: ingest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5
      - name: Terraform init
        working-directory: ./infra
        run: terraform init
      - name: Terraform apply
        working-directory: ./infra
        run: terraform apply -auto-approve
